server:
  port : 9090
spring:
  datasource:
    url: jdbc:mysql:/localhost:3306/mydb
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  cache:
    type: redis
spring.jpa.open-in-view : false
spring.data.redis.repositories.enabled : false
spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.servlet.context-path : /
redis:
  host: localhost
  port: 6379
  timeoutOfSeconds: 60
security:
  authentication:
    jwt:
      secret-key: mysql-db
      token-validity-in-seconds: 360000000
      token-validity-in-seconds-for-remember-me: 7200000000
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

log
